version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: exchange_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exchange_db
      MYSQL_USER: exchange_user
      MYSQL_PASSWORD: Windows123.
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: