quarkus.lambda.handler=main
quarkus.http.port=8080

#Conexion a MySQL en Docker
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=exchange_user
quarkus.datasource.password=Windows123.
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/exchange_db

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true